spring:
  application:
    name: cardatabase
  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:mariadb://localhost:3306/cardb
#    username: root
#    password: root
    url: jdbc:mariadb://hrr5mwqn9zs54rg4.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/tu4a75g4r05o8dc5
    username: gbq2i9spsn7sa7vm
    password: qkmii88vwlm9r5x2
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: api
#  h2:
#    console:
#      enabled: true
#      path: '/h2-console'
