spring:
  application:
    name: cardatabase
  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:mariadb://localhost:3306/cardb
#    username: root
#    password: root
    url: ${JAWSDB_MARIA_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      base-path: api
#  h2:
#    console:
#      enabled: true
#      path: '/h2-console'
